c = ['Aardvark', 'Abyssinian', 'Affenpinscher', 'Akbash', 'Akita', 'Albatross',
     'Alligator', 'Alpaca', 'Angelfish', 'Ant', 'Anteater', 'Antelope', 'Ape',
     'Armadillo', 'Ass', 'Avocet', 'Axolotl', 'Baboon', 'Badger', 'Balinese',
     'Bandicoot', 'Barb', 'Barnacle', 'Barracuda', 'Bat', 'Beagle', 'Bear',
     'Beaver', 'Bee', 'Beetle', 'Binturong', 'Bird', 'Birman', 'Bison',
     'Bloodhound', 'Boar', 'Bobcat', 'Bombay', 'Bongo', 'Bonobo', 'Booby',
     'Budgerigar', 'Buffalo', 'Bulldog', 'Bullfrog', 'Burmese', 'Butterfly',
     'Caiman', 'Camel', 'Capybara', 'Caracal', 'Caribou', 'Cassowary', 'Cat',
     'Caterpillar', 'Catfish', 'Cattle', 'Centipede', 'Chameleon', 'Chamois',
     'Cheetah', 'Chicken', 'Chihuahua', 'Chimpanzee', 'Chinchilla', 'Chinook', 
     'Chipmunk', 'Chough', 'Cichlid', 'Clam', 'Coati', 'Cobra', 'Cockroach',
     'Cod', 'Collie', 'Coral', 'Cormorant', 'Cougar', 'Cow', 'Coyote', 
     'Crab', 'Crane', 'Crocodile', 'Crow', 'Curlew', 'Cuscus', 'Cuttlefish',
     'Dachshund', 'Dalmatian', 'Deer', 'Dhole', 'Dingo', 'Dinosaur', 'Discus',
     'Dodo', 'Dog', 'Dogball', 'Dogfish', 'Dolphin', 'Donkey', 'Dormouse',
     'Dove', 'Dragonfly', 'Drever', 'Duck', 'Dugong', 'Dunker', 'Dunlin', 
     'Eagle', 'Earwig', 'Echidna', 'Eel', 'Eland', 'Elephant', 'ElephantSeal',
     'Elk', 'Emu', 'Falcon', 'Ferret', 'Finch', 'Fish', 'Flamingo', 'Flounder',
     'Fly', 'Fossa', 'Fox', 'Frigatebird', 'Frog', 'Galago', 'Gar', 'Gaur', 
     'Gazelle', 'Gecko', 'Gerbil', 'Gharial', 'GiantPanda', 'Gibbon', 'Giraffe',
     'Gnat', 'Gnu', 'Goat', 'Goldfinch', 'Goldfish', 'Goose', 'Gopher',
     'Gorilla', 'Goshawk', 'Grasshopper', 'Greyhound', 'Grouse', 'Guanaco', 
     'GuineaFowl', 'GuineaPig', 'Gull', 'Guppy', 'Hamster', 'Hare', 'Harrier', 
     'Havanese', 'Hawk', 'Hedgehog', 'Heron', 'Herring', 'Himalayan', 
     'Hippopotamus', 'Hornet', 'Horse', 'Human', 'Hummingbird', 'Hyena', 
     'Ibis', 'Iguana', 'Impala', 'Indri', 'Insect', 'Jackal', 'Jaguar', 
     'Javanese', 'Jay', 'Jellyfish', 'Kakapo', 'Kangaroo', 'Kingfisher', 
     'Kiwi', 'Koala', 'KomodoDragon', 'Kouprey', 'Kudu', 'Labradoodle', 
     'Ladybird', 'Lapwing', 'Lark', 'Lemming', 'Lemur', 'Leopard', 'Liger',
     'Lion', 'Lionfish', 'Lizard', 'Llama', 'Lobster', 'Locust', 'Loris', 
     'Louse', 'Lynx', 'Lyrebird', 'Macaw', 'Magpie', 'Mallard', 'Maltese',
     'Manatee', 'Mandrill', 'Markhor', 'Marten', 'Mastiff', 'Mayfly', 'Meerkat',
     'Millipede', 'Mink', 'Mole', 'Molly', 'Mongoose', 'Mongrel', 'Monkey',
     'Moorhen', 'Moose', 'Mosquito', 'Moth', 'Mouse', 'Mule', 'Narwhal',
     'Neanderthal', 'Newfoundland', 'Newt', 'Nightingale', 'Numbat', 'Ocelot',
     'Octopus', 'Okapi', 'Olm', 'Opossum', 'Orang-utan', 'Oryx', 'Ostrich', 
     'Otter', 'Owl', 'Ox', 'Oyster', 'Pademelon', 'Panther', 'Parrot',
     'Partridge', 'Peacock', 'Peafowl', 'Pekingese', 'Pelican', 'Penguin', 
     'Persian', 'Pheasant', 'Pig', 'Pigeon', 'Pika', 'Pike', 'Piranha', 
     'Platypus', 'Pointer', 'Pony', 'Poodle', 'Porcupine', 'Porpoise',
     'Possum', 'PrairieDog', 'Prawn', 'Puffin', 'Pug', 'Puma', 'Quail', 
     'Quelea', 'Quetzal', 'Quokka', 'Quoll', 'Rabbit', 'Raccoon', 'Ragdoll', 
     'Rail', 'Ram', 'Rat', 'Rattlesnake', 'Raven', 'RedDeer', 'RedPanda',
     'Reindeer', 'Rhinoceros', 'Robin', 'Rook', 'Rottweiler', 'Ruff',
     'Salamander', 'Salmon', 'SandDollar', 'Sandpiper', 'Saola', 
     'Sardine', 'Scorpion', 'SeaLion', 'SeaUrchin', 'Seahorse',
     'Seal', 'Serval', 'Shark', 'Sheep', 'Shrew', 'Shrimp', 'Siamese',
     'Siberian', 'Skunk', 'Sloth', 'Snail', 'Snake', 'Snowshoe', 'Somali', 
     'Sparrow', 'Spider', 'Sponge', 'Squid', 'Squirrel', 'Starfish', 'Starling',
     'Stingray', 'Stinkbug', 'Stoat', 'Stork', 'Swallow', 'Swan', 'Tang', 
     'Tapir', 'Tarsier', 'Termite', 'Tetra', 'Tiffany', 'Tiger', 'Toad', 
     'Tortoise', 'Toucan', 'Tropicbird', 'Trout', 'Tuatara', 'Turkey', 
     'Turtle', 'Uakari', 'Uguisu', 'Umbrellabird', 'Viper', 'Vulture',
     'Wallaby', 'Walrus', 'Warthog', 'Wasp', 'WaterBuffalo', 'Weasel',
     'Whale', 'Whippet', 'Wildebeest', 'Wolf', 'Wolverine', 'Wombat', 
     'Woodcock', 'Woodlouse', 'Woodpecker', 'Worm', 'Wrasse', 'Wren', 
     'Yak', 'Zebra', 'Zebu', 'Zonkey']
a = ['able', 'above', 'absent', 'absolute', 'abstract', 'abundant', 'academic',
     'acceptable', 'accepted', 'accessible', 'accurate', 'accused', 'active', 
     'actual', 'acute', 'added', 'additional', 'adequate', 'adjacent', 
     'administrative', 'adorable', 'advanced', 'adverse', 'advisory', 
     'aesthetic', 'afraid', 'african', 'aggregate', 'aggressive', 'agreeable', 
     'agreed', 'agricultural', 'alert', 'alive', 'alleged', 'allied', 'alone', 
     'alright', 'alternative', 'amateur', 'amazing', 'ambitious', 'american', 
     'amused', 'ancient', 'angry', 'annoyed', 'annual', 'anonymous', 'anxious', 
     'appalling', 'apparent', 'applicable', 'appropriate', 'arab', 'arbitrary',
     'architectural', 'armed', 'arrogant', 'artificial', 'artistic', 'ashamed', 
     'asian', 'asleep', 'assistant', 'associated', 'atomic', 'attractive',
     'australian', 'automatic', 'autonomous', 'available', 'average',
     'awake', 'aware', 'awful', 'awkward', 'back', 'bad', 'balanced', 'bare', 
     'basic', 'beautiful', 'beneficial', 'better', 'bewildered', 'big', 
     'binding', 'biological', 'bitter', 'bizarre', 'black', 'blank', 'blind', 
     'blonde', 'bloody', 'blue', 'blushing', 'boiling', 'bold', 'bored', 
     'boring', 'bottom', 'brainy', 'brave', 'breakable', 'breezy', 'brief', 
     'bright', 'brilliant', 'british', 'broad', 'broken', 'brown', 'bumpy', 
     'burning', 'busy', 'calm', 'canadian', 'capable', 'capitalist', 'careful',
     'casual', 'catholic', 'causal', 'cautious', 'central', 'certain', 
     'changing', 'characteristic', 'charming', 'cheap', 'cheerful', 'chemical', 
     'chief', 'chilly', 'chinese', 'chosen', 'christian', 'chronic', 'chubby', 
     'circular', 'civic', 'civil', 'civilian', 'classic', 'classical', 'clean',
     'clear', 'clever', 'clinical', 'close', 'closed', 'cloudy', 'clumsy', 
     'coastal', 'cognitive', 'coherent', 'cold', 'collective', 'colonial', 
     'colorful', 'colossal', 'coloured', 'colourful', 'combative', 'combined',
     'comfortable', 'coming', 'commercial', 'common', 'communist', 'compact', 
     'comparable', 'comparative', 'compatible', 'competent', 'competitive', 
     'complete', 'complex', 'complicated', 'comprehensive', 'compulsory',
     'conceptual', 'concerned', 'concrete', 'condemned', 'confident', 
     'confidential', 'confused', 'conscious', 'conservation', 'conservative',
     'considerable', 'consistent', 'constant', 'constitutional', 
     'contemporary', 'content', 'continental', 'continued', 'continuing', 
     'continuous', 'controlled', 'controversial', 'convenient', 'conventional',
     'convinced', 'convincing', 'cooing', 'cool', 'cooperative', 'corporate',
     'correct', 'corresponding', 'costly', 'courageous', 'crazy', 'creative', 
     'creepy', 'criminal', 'critical', 'crooked', 'crowded', 'crucial', 
     'crude', 'cruel', 'cuddly', 'cultural', 'curious', 'curly', 'current', 
     'curved', 'cute', 'daily', 'damaged', 'damp', 'dangerous', 'dark', 'dead',
     'deaf', 'deafening', 'dear', 'decent', 'decisive', 'deep', 'defeated', 
     'defensive', 'defiant', 'definite', 'deliberate', 'delicate', 'delicious',
     'delighted', 'delightful', 'democratic', 'dependent', 'depressed', 
     'desirable', 'desperate', 'detailed', 'determined', 'developed', 
     'developing', 'devoted', 'different', 'difficult', 'digital', 'diplomatic', 
     'direct', 'dirty', 'disabled', 'disappointed', 'disastrous', 
     'disciplinary', 'disgusted', 'distant', 'distinct', 'distinctive',
     'distinguished', 'disturbed', 'disturbing', 'diverse', 'divine', 'dizzy', 
     'domestic', 'dominant', 'double', 'doubtful', 'drab', 'dramatic',
     'dreadful', 'driving', 'drunk', 'dry', 'dual', 'due', 'dull', 'dusty',
     'dutch', 'dying', 'dynamic', 'eager', 'early', 'eastern', 'easy', 
     'economic', 'educational', 'eerie', 'effective', 'efficient', 
     'elaborate', 'elated', 'elderly', 'eldest', 'electoral', 'electric',
     'electrical', 'electronic', 'elegant', 'eligible', 'embarrassed',
     'embarrassing', 'emotional', 'empirical', 'empty', 'enchanting',
     'encouraging', 'endless', 'energetic', 'english', 'enormous', 
     'enthusiastic', 'entire', 'entitled', 'envious', 'environmental', 'equal', 
     'equivalent', 'essential', 'established', 'estimated', 'ethical', 
     'ethnic', 'european', 'eventual', 'everyday', 'evident', 'evil', 
     'evolutionary', 'exact', 'excellent', 'exceptional', 'excess', 
     'excessive', 'excited', 'exciting', 'exclusive', 'existing', 'exotic', 
     'expected', 'expensive', 'experienced', 'experimental', 'explicit',
     'extended', 'extensive', 'external', 'extra', 'extraordinary', 'extreme', 
     'exuberant', 'faint', 'fair', 'faithful', 'familiar', 'famous', 'fancy',
     'fantastic', 'far', 'fascinating', 'fashionable', 'fast', 'fat', 'fatal', 
     'favourable', 'favourite', 'federal', 'fellow', 'female', 'feminist', 
     'few', 'fierce', 'filthy', 'final', 'financial', 'fine', 'firm', 'fiscal', 
     'fit', 'fixed', 'flaky', 'flat', 'flexible', 'fluffy', 'fluttering', 
     'flying', 'following', 'fond', 'foolish', 'foreign', 'formal', 
     'formidable', 'forthcoming', 'fortunate', 'forward', 'fragile', 
     'frail', 'frantic', 'free', 'french', 'frequent', 'fresh', 'friendly', 
     'frightened', 'front', 'frozen', 'fucking', 'full', 'full-time', 'fun',
     'functional', 'fundamental', 'funny', 'furious', 'future', 'fuzzy',
     'gastric', 'gay', 'general', 'generous', 'genetic', 'gentle', 'genuine',
     'geographical', 'german', 'giant', 'gigantic', 'given', 'glad',
     'glamorous', 'gleaming', 'global', 'glorious', 'golden', 'good', 
     'gorgeous', 'gothic', 'governing', 'graceful', 'gradual', 'grand', 
     'grateful', 'greasy', 'great', 'greek', 'green', 'grey', 'grieving',
     'grim', 'gross', 'grotesque', 'growing', 'grubby', 'grumpy', 'guilty',
     'handicapped', 'handsome', 'happy', 'hard', 'harsh', 'head', 'healthy', 
     'heavy', 'helpful', 'helpless', 'hidden', 'high', 'high-pitched',
     'hilarious', 'hissing', 'historic', 'historical', 'hollow', 'holy',
     'homeless', 'homely', 'hon', 'honest', 'horizontal', 'horrible', 
     'hostile', 'hot', 'huge', 'human', 'hungry', 'hurt', 'hushed', 'husky',
     'icy', 'ideal', 'identical', 'ideological', 'ill', 'illegal', 
     'imaginative', 'immediate', 'immense', 'imperial', 'implicit', 
     'important', 'impossible', 'impressed', 'impressive', 'improved', 
     'inadequate', 'inappropriate', 'inc', 'inclined', 'increased', 
     'increasing', 'incredible', 'independent', 'indian', 'indirect', 
     'individual', 'industrial', 'inevitable', 'influential', 'informal',
     'inherent', 'initial', 'injured', 'inland', 'inner', 'innocent', 
     'innovative', 'inquisitive', 'instant', 'institutional', 'insufficient',
     'intact', 'integral', 'integrated', 'intellectual', 'intelligent', 
     'intense', 'intensive', 'interested', 'interesting', 'interim', 
     'interior', 'intermediate', 'internal', 'international', 'intimate',
     'invisible', 'involved', 'iraqi', 'irish', 'irrelevant', 'islamic',
     'isolated', 'israeli', 'italian', 'itchy', 'japanese', 'jealous', 
     'jewish', 'jittery', 'joint', 'jolly', 'joyous', 'judicial', 'juicy', 
     'junior', 'just', 'keen', 'key', 'kind', 'known', 'korean', 'labour', 
     'large', 'large-scale', 'late', 'latin', 'lazy', 'leading', 'left', 
     'legal', 'legislative', 'legitimate', 'lengthy', 'lesser', 'level', 
     'lexical', 'liable', 'liberal', 'light', 'like', 'likely', 'limited', 
     'linear', 'linguistic', 'liquid', 'literary', 'little', 'live', 'lively', 
     'living', 'local', 'logical', 'lonely', 'long', 'long-term', 'loose', 
     'lost', 'loud', 'lovely', 'low', 'loyal', 'ltd', 'lucky', 'mad',
     'magenta', 'magic', 'magnetic', 'magnificent', 'main', 'major', 'male',
     'mammoth', 'managerial', 'managing', 'manual', 'many', 'marginal', 
     'marine', 'marked', 'married', 'marvellous', 'marxist', 'mass', 'massive', 
     'mathematical', 'mature', 'maximum', 'mean', 'meaningful', 'mechanical',
     'medical', 'medieval', 'melodic', 'melted', 'mental', 'mere', 
     'metropolitan', 'mid', 'middle', 'middle-class', 'mighty', 'mild',
     'military', 'miniature', 'minimal', 'minimum', 'ministerial', 'minor', 
     'miserable', 'misleading', 'missing', 'misty', 'mixed', 'moaning', 
     'mobile', 'moderate', 'modern', 'modest', 'molecular', 'monetary', 
     'monthly', 'moral', 'motionless', 'muddy', 'multiple', 'mushy', 
     'musical', 'mute', 'mutual', 'mysterious', 'naked', 'narrow', 'nasty',
     'national', 'native', 'natural', 'naughty', 'naval', 'near', 'nearby', 
     'neat', 'necessary', 'negative', 'neighbouring', 'nervous', 'net', 
     'neutral', 'new', 'nice', 'nineteenth-century', 'noble', 'noisy', 
     'normal', 'northern', 'nosy', 'notable', 'novel', 'nuclear', 'numerous',
     'nursing', 'nutritious', 'nutty', 'obedient', 'objective', 'obliged', 
     'obnoxious', 'obvious', 'occasional', 'occupational', 'odd', 'official',
     'ok', 'okay', 'old', 'old-fashioned', 'olympic', 'only', 'open', 
     'operational', 'opposite', 'optimistic', 'oral', 'orange', 'ordinary', 
     'organic', 'organisational', 'original', 'orthodox', 'other', 'outdoor', 
     'outer', 'outrageous', 'outside', 'outstanding', 'overall', 'overseas',
     'overwhelming', 'painful', 'pale', 'palestinian', 'panicky', 'parallel', 
     'parental', 'parliamentary', 'part-time', 'partial', 'particular', 
     'passing', 'passive', 'past', 'patient', 'payable', 'peaceful', 
     'peculiar', 'perfect', 'permanent', 'persistent', 'personal', 'petite',
     'philosophical', 'physical', 'pink', 'plain', 'planned', 'plastic',
     'pleasant', 'pleased', 'poised', 'polish', 'polite', 'political', 'poor', 
     'popular', 'positive', 'possible', 'post-war', 'potential', 'powerful',
     'practical', 'precious', 'precise', 'preferred', 'pregnant', 
     'preliminary', 'premier', 'prepared', 'present', 'presidential', 
     'pretty', 'previous', 'prickly', 'primary', 'prime', 'primitive', 
     'principal', 'printed', 'prior', 'private', 'probable', 'productive',
     'professional', 'profitable', 'profound', 'progressive', 'prominent', 
     'promising', 'proper', 'proposed', 'prospective', 'protective', 
     'protestant', 'proud', 'provincial', 'psychiatric', 'psychological',
     'public', 'puny', 'pure', 'purple', 'purring', 'puzzled', 'quaint', 
     'qualified', 'quick', 'quickest', 'quiet', 'racial', 'radical', 'rainy',
     'random', 'rapid', 'rare', 'raspy', 'rational', 'ratty', 'raw', 'ready', 
     'real', 'realistic', 'rear', 'reasonable', 'recent', 'red', 'reduced',
     'redundant', 'regional', 'registered', 'regular', 'regulatory', 'related', 
     'relative', 'relaxed', 'relevant', 'reliable', 'relieved', 'religious',
     'reluctant', 'remaining', 'remarkable', 'remote', 'renewed',
     'representative', 'repulsive', 'required', 'resident', 'residential',
     'resonant', 'respectable', 'respective', 'responsible', 'resulting',
     'retail', 'retired', 'revolutionary', 'rich', 'ridiculous', 'right',
     'rigid', 'ripe', 'rising', 'rival', 'roasted', 'robust', 'rolling', 
     'roman', 'romantic', 'rotten', 'rough', 'round', 'royal', 'rubber',
     'rude', 'ruling', 'running', 'rural', 'russian', 'sacred', 'sad', 'safe',
     'salty', 'satisfactory', 'satisfied', 'scared', 'scary', 'scattered',
     'scientific', 'scornful', 'scottish', 'scrawny', 'screeching', 
     'secondary', 'secret', 'secure', 'select', 'selected', 'selective', 
     'selfish', 'semantic', 'senior', 'sensible', 'sensitive', 'separate',
     'serious', 'severe', 'sexual', 'shaggy', 'shaky', 'shallow', 'shared', 
     'sharp', 'sheer', 'shiny', 'shivering', 'shocked', 'short', 'short-term', 
     'shrill', 'shy', 'sick', 'significant', 'silent', 'silky', 'silly', 
     'similar', 'simple', 'single', 'skilled', 'skinny', 'sleepy', 'slight',
     'slim', 'slimy', 'slippery', 'slow', 'small', 'smart', 'smiling', 
     'smoggy', 'smooth', 'so-called', 'social', 'socialist', 'soft', 'solar',
     'sole', 'solid', 'sophisticated', 'sore', 'sorry', 'sound', 'sour', 
     'southern', 'soviet', 'spanish', 'spare', 'sparkling', 'spatial', 
     'special', 'specific', 'specified', 'spectacular', 'spicy', 'spiritual',
     'splendid', 'spontaneous', 'sporting', 'spotless', 'spotty', 'square', 
     'squealing', 'stable', 'stale', 'standard', 'static', 'statistical', 
     'statutory', 'steady', 'steep', 'sticky', 'stiff', 'still', 'stingy',
     'stormy', 'straight', 'straightforward', 'strange', 'strategic',
     'strict', 'striking', 'striped', 'strong', 'structural', 'stuck', 
     'stupid', 'subjective', 'subsequent', 'substantial', 'subtle', 
     'successful', 'successive', 'sudden', 'sufficient', 'suitable',
     'sunny', 'super', 'superb', 'superior', 'supporting', 'supposed',
     'supreme', 'sure', 'surprised', 'surprising', 'surrounding', 
     'surviving', 'suspicious', 'sweet', 'swift', 'swiss', 'symbolic',
     'sympathetic', 'systematic', 'tall', 'tame', 'tan', 'tart',
     'tasteless', 'tasty', 'technical', 'technological', 'teenage', 
     'temporary', 'tender', 'tense', 'terrible', 'territorial', 'testy',
     'then', 'theoretical', 'thick', 'thin', 'thirsty', 'thorough', 
     'thoughtful', 'thoughtless', 'thundering', 'tight', 'tiny', 'tired',
     'top', 'tory', 'total', 'tough', 'toxic', 'traditional', 'tragic', 
     'tremendous', 'tricky', 'tropical', 'troubled', 'turkish', 'typical', 
     'ugliest', 'ugly', 'ultimate', 'unable', 'unacceptable', 'unaware', 
     'uncertain', 'unchanged', 'uncomfortable', 'unconscious', 'underground',
     'underlying', 'unemployed', 'uneven', 'unexpected', 'unfair', 
     'unfortunate', 'unhappy', 'uniform', 'uninterested', 'unique', 'united',
     'universal', 'unknown', 'unlikely', 'unnecessary', 'unpleasant', 
     'unsightly', 'unusual', 'unwilling', 'upper', 'upset', 'uptight', 
     'urban', 'urgent', 'used', 'useful', 'useless', 'usual', 'vague', 
     'valid', 'valuable', 'variable', 'varied', 'various', 'varying', 'vast',
     'verbal', 'vertical', 'very', 'victorian', 'victorious', 'video-taped', 
     'violent', 'visible', 'visiting', 'visual', 'vital', 'vivacious', 
     'vivid', 'vocational', 'voiceless', 'voluntary', 'vulnerable', 
     'wandering', 'warm', 'wasteful', 'watery', 'weak', 'wealthy', 'weary', 
     'wee', 'weekly', 'weird', 'welcome', 'well', 'well-known', 'welsh', 
     'western', 'wet', 'whispering', 'white', 'whole', 'wicked', 'wide',
     'wide-eyed', 'widespread', 'wild', 'willing', 'wise', 'witty', 
     'wonderful', 'wooden', 'working', 'working-class', 'worldwide',
     'worried', 'worrying', 'worthwhile', 'worthy', 'written', 'wrong',
     'yellow', 'young', 'yummy', 'zany', 'zealous']
b = ['abiding', 'accelerating', 'accepting', 'accomplishing', 'achieving', 
'acquiring', 'acteding', 'activating', 'adapting', 'adding', 'addressing', 
'administering', 'admiring', 'admiting', 'adopting', 'advising', 'affording', 
'agreeing', 'alerting', 'alighting', 'allowing', 'altereding', 'amusing', 
'analyzing', 'announcing', 'annoying', 'answering', 'anticipating', 
'apologizing', 'appearing', 'applauding', 'applieding', 'appointing',
 'appraising', 'appreciating', 'approving', 'arbitrating', 'arguing', 
 'arising', 'arranging', 'arresting', 'arriving', 'ascertaining', 'asking', 
 'assembling', 'assessing', 'assisting', 'assuring', 'attaching', 'attacking', 
 'attaining', 'attempting', 'attending', 'attracting', 'auditeding', 'avoiding',
 'awaking', 'backing', 'baking', 'balancing', 'baning', 'banging', 'baring', 
 'bating', 'bathing', 'battling', 'bing', 'beaming', 'bearing', 'beating', 
 'becoming', 'beging', 'begining', 'behaving', 'beholding', 'belonging', 
 'bending', 'beseting', 'beting', 'biding', 'binding', 'biting', 'bleaching',
 'bleeding', 'blessing', 'blinding', 'blinking', 'bloting', 'blowing', 
 'blushing', 'boasting', 'boiling', 'bolting', 'bombing', 'booking', 
 'boring', 'borrowing', 'bouncing', 'bowing', 'boxing', 'braking', 
 'branching', 'breaking', 'breathing', 'breeding', 'briefing', 'bringing',
 'broadcasting', 'bruising', 'brushing', 'bubbling', 'budgeting', 'building', 
 'bumping', 'burning', 'bursting', 'burying', 'busting', 'buying', 'buzing', 
 'calculating', 'calling', 'camping', 'caring', 'carrying', 'carving', 
 'casting', 'cataloging', 'catching', 'causing', 'challenging', 'changing',
 'charging', 'charting', 'chasing', 'cheating', 'checking', 'cheering', 
 'chewing', 'choking', 'choosing', 'choping', 'claiming', 'claping', 
 'clarifying', 'classifying', 'cleaning', 'clearing', 'clinging', 'cliping',
 'closing', 'clothing', 'coaching', 'coiling', 'collecting', 'coloring', 
 'combing', 'coming', 'commanding', 'communicating', 'comparing', 'competing',
 'compiling', 'complaining', 'completing', 'composing', 'computing',
 'conceiving', 'concentrating', 'conceptualizing', 'concerning', 'concluding',
 'conducting', 'confessing', 'confronting', 'confusing', 'connecting', 
 'conserving', 'considering', 'consisting', 'consolidating', 'constructing',
 'consulting', 'containing', 'continuing', 'contracting', 'controling', 
 'converting', 'coordinating', 'copying', 'correcting', 'correlating',
 'costing', 'coughing', 'counseling', 'counting', 'covering', 'cracking',
 'crashing', 'crawling', 'creating', 'creeping', 'critiquing', 'crossing', 
 'crushing', 'crying', 'curing', 'curling', 'curving', 'cuting', 'cycling',
 'daming', 'damaging', 'dancing', 'daring', 'dealing', 'decaying', 'deceiving',
 'deciding', 'decorating', 'defining', 'delaying', 'delegating', 'delighting',
 'delivering', 'demonstrating', 'depending', 'describing', 'deserting', 
 'deserving', 'designing', 'destroying', 'detailing', 'detecting', 
 'determining', 'developing', 'devising', 'diagnosing', 'diging', 
 'directing', 'disagreing', 'disappearing', 'disapproving', 'disarming', 
 'discovering', 'disliking', 'dispensing', 'displaying', 'disproving',
 'dissecting', 'distributing', 'diving', 'diverting', 'dividing', 'doing',
 'doubling', 'doubting', 'drafting', 'draging', 'draining', 'dramatizing', 
 'drawing', 'dreaming', 'dressing', 'drinking', 'driping', 'driving', 
 'dropping', 'drowning', 'druming', 'drying', 'dusting', 'dwelling',
 'earning', 'eating', 'editeding', 'educating', 'eliminating',
 'embarrassing', 'employing', 'emptying', 'enacteding', 'encouraging',
 'ending', 'enduring', 'enforcing', 'engineering', 'enhancing',
 'enjoying', 'enlisting', 'ensuring', 'entering', 'entertaining',
 'escaping', 'establishing', 'estimating', 'evaluating', 'examining',
 'exceeding', 'exciting', 'excusing', 'executing', 'exercising', 'exhibiting',
 'existing', 'expanding', 'expecting', 'expediting', 'experimenting', 
 'explaining', 'exploding', 'expressing', 'extending', 'extracting', 
 'facing', 'facilitating', 'fading', 'failing', 'fancying', 'fastening', 
 'faxing', 'fearing', 'feeding', 'feeling', 'fencing', 'fetching', 'fighting', 
 'filing', 'filling', 'filming', 'finalizing', 'financing', 'finding',
 'firing', 'fiting', 'fixing', 'flaping', 'flashing', 'fleing', 'flinging',
 'floating', 'flooding', 'flowing', 'flowering', 'flying', 'folding', 
 'following', 'fooling', 'forbiding', 'forcing', 'forecasting', 'foregoing', 
 'foreseing', 'foretelling', 'forgeting', 'forgiving', 'forming', 
 'formulating', 'forsaking', 'framing', 'freezing', 'frightening', 'frying',
 'gathering', 'gazing', 'generating', 'geting', 'giving', 'glowing', 'gluing', 
 'going', 'governing', 'grabing', 'graduating', 'grating', 'greasing', 'greeting',
 'grinning', 'grinding', 'griping', 'groaning', 'growing', 'guaranteeing',
 'guarding', 'guessing', 'guiding', 'hammering', 'handing', 'handling', 
 'handwriting', 'hanging', 'happening', 'harassing', 'harming', 'hating',
 'haunting', 'heading', 'healing', 'heaping', 'hearing', 'heating', 'helping', 
 'hiding', 'hitting', 'holding', 'hooking', 'hoping', 'hopping', 'hovering',
 'hugging', 'hmuming', 'hunting', 'hurrying', 'hurting', 'hypothesizing', 
 'identifying', 'ignoring', 'illustrating', 'imagining', 'implementing', 
 'impressing', 'improving', 'improvising', 'including', 'increasing', 
 'inducing', 'influencing', 'informing', 'initiating', 'injecting', 
 'injuring', 'inlaying', 'innovating', 'inputing', 'inspecting', 
 'inspiring', 'installing', 'instituting', 'instructing', 'insuring', 
 'integrating', 'intending', 'intensifying', 'interesting', 
 'interfering', 'interlaying', 'interpreting', 'interrupting', 
 'interviewing', 'introducing', 'inventing', 'inventorying', 
 'investigating', 'inviting', 'irritating', 'itching', 'jailing', 
 'jamming', 'jogging', 'joining', 'joking', 'judging', 'juggling', 'jumping',
 'justifying', 'keeping', 'kepting', 'kicking', 'killing', 'kissing', 'kneeling',
 'kniting', 'knocking', 'knotting', 'knowing', 'labeling', 'landing', 'lasting',
 'laughing', 'launching', 'laying', 'leading', 'leaning', 'leaping', 'learning', 
 'leaving', 'lecturing', 'leding', 'lending', 'leting', 'leveling', 
 'licensing', 'licking', 'lying', 'lifteding', 'lighting', 'lightening',
 'liking', 'listing', 'listening', 'living', 'loading', 'locating', 
 'locking', 'loging', 'longing', 'looking', 'losing', 'loving', 
 'maintaining', 'making', 'maning', 'managing', 'manipulating', 
 'manufacturing', 'mapping', 'marching', 'marking', 'marketing',
 'marrying', 'matching', 'mating', 'mattering', 'meaning', 'measuring',
 'meddling', 'mediating', 'meeting', 'melting', 'melting', 'memorizing',
 'mending', 'mentoring', 'milking', 'mining', 'misleading', 'missing',
 'misspelling', 'mistaking', 'misunderstanding', 'mixing', 'moaning', 
 'modeling', 'modifying', 'monitoring', 'mooring', 'motivating',
 'mourning', 'moving', 'mowing', 'muddling', 'muging', 'multiplying', 
 'murdering', 'nailing', 'naming', 'navigating', 'needing', 'negotiating', 
 'nesting', 'noding', 'nominating', 'normalizing', 'noting', 'noticing', 
 'numbering', 'obeying', 'objecting', 'observing', 'obtaining', 'occuring', 
 'offending', 'offering', 'officiating', 'opening', 'operating', 'ordering', 
 'organizing', 'orienteding', 'originating', 'overcoming', 'overdoing', 
 'overdrawing', 'overflowing', 'overhearing', 'overtaking', 'overthrowing',
 'owing', 'owning', 'packing', 'paddling', 'painting', 'parking', 'parting', 
 'participating', 'passing', 'pasting', 'pating', 'pausing', 'paying',
 'pecking', 'pedaling', 'peeling', 'peeping', 'perceiving', 'perfecting', 
 'performing', 'permiting', 'persuading', 'phoning', 'photographing',
 'picking', 'piloting', 'pinching', 'pining', 'pinpointing', 'pioneering',
 'placing', 'planing', 'planting', 'playing', 'pleading', 'pleasing',
 'plugging', 'pointing', 'poking', 'polishing', 'poping', 'possessing',
 'posting', 'pouring', 'practicing', 'praiseding', 'praying', 'preaching', 
 'preceding', 'predicting', 'prefering', 'preparing', 'prescribing', 
 'presenting', 'preserving', 'preseting', 'presiding', 'pressing', 
 'pretending', 'preventing', 'pricking', 'printing', 'processing', 
 'procuring', 'producing', 'professing', 'programing', 'progressing', 
 'projecting', 'promising', 'promoting', 'proofreading', 'proposing', 
 'protecting', 'proving', 'providing', 'publicizing', 'pulling', 'pumping',
 'punching', 'puncturing', 'punishing', 'purchasing', 'pushing', 'puting',
 'qualifying', 'questioning', 'queuing', 'quiting', 'racing', 'radiating',
 'raining', 'raising', 'ranking', 'rating', 'reaching', 'reading', 
 'realigning', 'realizing', 'reasoning', 'receiving', 'recognizing', 
 'recommending', 'reconciling', 'recording', 'recruiting', 'reducing', 
 'referring', 'reflecting', 'refusing', 'regreting', 'regulating', 
 'rehabilitating', 'reigning', 'reinforcing', 'rejecting', 'rejoicing',
 'relating', 'relaxing', 'releasing', 'relying', 'remaining', 'remembering',
 'reminding', 'removing', 'rendering', 'reorganizing', 'repairing',
 'repeating', 'replacing', 'replying', 'reporting', 'representing',
 'reproducing', 'requesting', 'rescuing', 'researching', 'resolving', 
 'responding', 'restoreding', 'restructuring', 'retiring', 'retrieving',
 'returning', 'reviewing', 'revising', 'rhyming', 'riding', 'riding', 
 'ringing', 'rinsing', 'rising', 'risking', 'robing', 'rocking', 'rolling',
 'roting', 'rubing', 'ruining', 'ruling', 'runing', 'rushing', 'sacking',
 'sailing', 'satisfying', 'saving', 'sawing', 'saying', 'scaring', 
 'scattering', 'scheduling', 'scolding', 'scorching', 'scraping', 
 'scratching', 'screaming', 'screwing', 'scribbling', 'scrubing', 
 'sealing', 'searching', 'securing', 'seing', 'seeking', 'selecting', 
 'selling', 'sending', 'sensing', 'separating', 'serving', 'servicing', 
 'seting', 'settling', 'sewing', 'shading', 'shaking', 'shaping', 
 'sharing', 'shaving', 'shearing', 'sheding', 'sheltering', 'shining', 
 'shivering', 'shocking', 'shoing', 'shooting', 'shoping', 'showing', 
 'shrinking', 'shruging', 'shuting', 'sighing', 'signing', 'signaling',
 'simplifying', 'sining', 'singing', 'sinking', 'siping', 'siting',
 'sketching', 'skiing', 'skiping', 'slaping', 'slaying', 'sleeping',
 'sliding', 'slinging', 'slinking', 'sliping', 'sliting', 'slowing',
 'smashing', 'smelling', 'smiling', 'smiting', 'smoking', 'snatching',
 'sneaking', 'sneezing', 'sniffing', 'snoring', 'snowing', 'soaking', 
 'solving', 'soothing', 'soothsaying', 'sorting', 'sounding', 'sowing', 
 'sparing', 'sparking', 'sparkling', 'speaking', 'specifying', 'speeding',
 'spelling', 'spending', 'spilling', 'spining', 'spiting', 'spliting',
 'spoiling', 'spoting', 'spraying', 'spreading', 'springing', 'sprouting', 
 'squashing', 'squeaking', 'squealing', 'squeezing', 'staining', 'stamping',
 'standing', 'staring', 'starting', 'staying', 'stealing', 'steering', 
 'stepping', 'sticking', 'stimulating', 'stinging', 'stinking', 'stirring', 
 'stitching', 'stoping', 'storing', 'straping', 'streamlining', 
 'strengthening', 'stretching', 'striding', 'striking', 'stringing', 
 'stripping', 'striving', 'stroking', 'structuring', 'studying', 
 'stuffing', 'subleting', 'subtracting', 'succeeding', 'sucking', 
 'suffering', 'suggesting', 'suiting', 'summarizing', 'supervising',
 'supplying', 'supporting', 'supposing', 'surprising', 'surrounding', 
 'suspecting', 'suspending', 'swearing', 'sweating', 'sweeping', 'swelling', 
 'swimming', 'swinging', 'switching', 'symbolizing', 'synthesizing',
 'systemizing', 'tabulating', 'taking', 'talking', 'taming', 'taping', 
 'targeting', 'tasting', 'teaching', 'tearing', 'teasing', 'telephoning', 
 'telling', 'tempting', 'terrifying', 'testing', 'thanking', 'thawing', 
 'thinking', 'thriving', 'throwing', 'thrusting', 'ticking', 'tickling', 
 'tying', 'timing', 'tiping', 'tiring', 'touching', 'touring', 'towing',
 'tracing', 'trading', 'training', 'transcribing', 'transfering',
 'transforming', 'translating', 'transporting', 'traping', 'traveling',
 'treading', 'treating', 'trembling', 'tricking', 'triping', 'troting', 
 'troubling', 'troubleshooting', 'trusting', 'trying', 'tuging', 'tumbling',
 'turning', 'tutoring', 'twisting', 'typing', 'undergoing', 'understanding',
 'undertaking', 'undressing', 'unfastening', 'unifying', 'uniting', 
 'unlocking', 'unpacking', 'untidying', 'updating', 'upgrading', 
 'upholding', 'upseting', 'using', 'utilizing', 'vanishing', 'verbalizing',
 'verifying', 'vexing', 'visiting', 'wailing', 'waiting', 'waking', 
 'walking', 'wandering', 'wanting', 'warming', 'warning', 'washing', 
 'wasting', 'watching', 'watering', 'waving', 'wearing', 'weaving', 
 'wedding', 'weeping', 'weighing', 'welcoming', 'wending', 'weting', 
 'whining', 'whiping', 'whirling', 'whispering', 'whistling', 'wining', 
 'winding', 'winking', 'wiping', 'wishing', 'withdrawing', 'withholding',
 'withstanding', 'wobbling', 'wondering', 'working', 'worrying', 'wrapping', 
 'wrecking', 'wrestling', 'wriggling', 'wringing', 'writing', 'x-raying',
 'yawning', 'yelling', 'zipping', 'zooming']