#!/usr/bin/env python3
"""Status tables, generated. Stdlib only.

    python tools/status.py            # rewrite every generated region in place
    python tools/status.py --check    # exit 1 if any generated region is stale (CI)

Every MODULES.md used to carry a hand-copied status table whose header claimed the numbers were
"written back by tools/execute.py and tools/grade.py". Neither tool wrote that file, and the
tables went stale twice: rubric points changed under review and nobody re-copied them. So the
tables are now GENERATED, between markers, from the only sources that can be trusted:

  * which modules exist ........ the lesson directories themselves
  * module numbers and titles .. each MODULES.md's own "## N." / "## Module N —" headings
  * built vs in review ......... meta.yaml `status` (reviewed = built)
  * seconds and peak MiB ....... meta.yaml, as MEASURED and written back by tools/execute.py
  * rubric points and cases .... parsed from tests/test_lesson.py's RUBRIC -- never typed

Edit the lessons, not the tables.
"""
import ast, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- STATUS:BEGIN generated by tools/status.py from the lessons themselves; do not edit -->"
END = "<!-- STATUS:END -->"
HEADING = re.compile(r"^## (?:Module )?(\d+)(?:\.|\s+—)\s+(.+?)\s*$", re.M)
STATUS_SUFFIX = re.compile(r"\s*(?:—\s*)?(?:\*\*BUILT\*\*|\*\(?specified\)?\*|\*specified\*)\s*$")


def meta(d: Path) -> dict:
    out = {}
    for line in (d / "meta.yaml").read_text().splitlines():
        m = re.match(r"^([a-z_]+):\s*(.+?)\s*$", line)
        if m:
            out[m.group(1)] = re.sub(r"\s+#.*$", "", m.group(2)).strip().strip('"\'')
    return out


def rubric(d: Path) -> tuple:
    """(points, cases) summed from the RUBRIC list literal in tests/test_lesson.py."""
    tree = ast.parse((d / "tests" / "test_lesson.py").read_text())
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and any(getattr(t, "id", "") == "RUBRIC" for t in node.targets):
            rows = [e for e in node.value.elts if isinstance(e, ast.Tuple)]
            pts = sum(e.elts[1].value for e in rows if isinstance(e.elts[1], ast.Constant))
            return pts, len(rows)
    return 0, 0


def fmt_secs(s: str) -> str:
    try:
        v = float(s)
    except (TypeError, ValueError):
        return "—"
    return "<0.1 s" if v < 0.1 else f"{v:.1f} s"


def programme_rows(prog: Path) -> list:
    text = (prog / "MODULES.md").read_text()
    lessons = {int(m.group(1)): p for p in (prog / "lessons").glob("*/")
               if (m := re.match(r"P\d\d-L(\d\d)", p.name)) and (p / "meta.yaml").exists()}
    rows = []
    for m in HEADING.finditer(text):
        n = int(m.group(1))
        title = STATUS_SUFFIX.sub("", m.group(2))
        title = re.split(r"\s+—\s+", title, maxsplit=1)[0].strip()
        head, sep, _ = title.partition(": ")
        if sep and len(head.split()) >= 3:      # "Capstone: a monitoring programme ..." keeps its name
            title = head
        d = lessons.get(n)
        if d is None:
            rows.append((n, title, "specified", "—", "—", "—", "—"))
            continue
        mt = meta(d)
        pts, cases = rubric(d)
        status = "**built**" if mt.get("status") == "reviewed" else f"in review ({mt.get('status', '?')})"
        lang = {"c": "**C**", "cpp": "**C++**"}.get(mt.get("language", "python"), "python")
        measured = f"{fmt_secs(mt.get('measured_seconds'))} · {mt.get('measured_peak_mib', '—')} MiB"
        rows.append((n, title, status, f"`{d.name}`", lang, measured, f"{pts} pts / {cases} cases"))
    return sorted(rows)


def programme_region(prog: Path) -> str:
    rows = programme_rows(prog)
    built = sum(r[2] == "**built**" for r in rows)
    lines = [BEGIN, "",
             f"**{built} of {len(rows)} modules built.** A module is built when its lesson directory "
             "exists and has passed all 14 gates in `QUALITY.md` and an independent review; "
             "everything else is specified here and has no directory. Seconds and peak memory are "
             "measured by `tools/execute.py`; rubric size is read from each lesson's "
             "`tests/test_lesson.py`. Regenerate with `python tools/status.py`.", "",
             "| # | Module | Status | Lesson | Language | Measured | Rubric |",
             "|---|---|---|---|---|---|---|"]
    lines += [f"| {n} | {t} | {s} | {l} | {lang} | {me} | {ru} |" for n, t, s, l, lang, me, ru in rows]
    return "\n".join(lines + ["", END])


def readme_region() -> str:
    def count(pattern):
        ds = [p for p in ROOT.glob(pattern) if (p / "meta.yaml").exists()]
        return ds, sum(meta(p).get("status") == "reviewed" for p in ds)
    rows, total = [], 0
    for fl in sorted(ROOT.glob("flagships/*/")):
        ds, ok = count(f"flagships/{fl.name}/lessons/*/")
        total += len(ds)
        rows.append(f"| `flagships/{fl.name}` | {ok} lessons{' + capstone' if (fl / 'capstone').is_dir() else ''} | — |")
    ds, ok = count("lessons/*/")
    total += len(ds)
    rows.append(f"| `lessons/` — track lessons | {ok} | — |")
    for prog in sorted(ROOT.glob("programmes/*/")):
        r = programme_rows(prog)
        b = sum(x[2] == "**built**" for x in r)
        total += sum(x[3] != "—" for x in r)
        rows.append(f"| `programmes/{prog.name}` | {b} of {len(r)} | {len(r) - b} |")
    every = [p for pat in ("lessons/*/", "flagships/*/lessons/*/", "programmes/*/lessons/*/")
             for p in ROOT.glob(pat) if (p / "meta.yaml").exists()]
    compiled = sum(meta(p).get("language") in ("c", "cpp") for p in every)
    reviewed = sum(meta(p).get("status") == "reviewed" for p in every)
    headline = (f"**{total} lessons, every one passing all 14 gates in `QUALITY.md` and independently "
                "reviewed.**" if reviewed == total == len(every) else
                f"**{len(every)} lessons, {reviewed} of them passed and independently reviewed.**")
    return "\n".join([BEGIN, "",
        f"{headline} {compiled} are compiled C or C++ exercises. Every notebook opens in Colab, "
        "Kaggle, Binder, Codespaces or local Jupyter. Every `MODULES.md` marks a module built only "
        "when its lesson exists and has passed; everything else says `specified`, and means it.", "",
        "| Area | Built | Specified, not built |", "|---|---|---|", *rows, "", END])


def splice(path: Path, region: str) -> tuple:
    text = path.read_text()
    if BEGIN not in text:
        return text, None
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: region, text, flags=re.S)
    return text, new


def main() -> int:
    check = "--check" in sys.argv
    targets = [(p / "MODULES.md", programme_region(p)) for p in sorted(ROOT.glob("programmes/*/"))]
    targets.append((ROOT / "README.md", readme_region()))
    stale = 0
    for path, region in targets:
        old, new = splice(path, region)
        rel = path.relative_to(ROOT)
        if new is None:
            print(f"  NO MARKERS  {rel}")
            stale += 1
        elif new == old:
            print(f"  current     {rel}")
        elif check:
            print(f"  STALE       {rel}  (run: python tools/status.py)")
            stale += 1
        else:
            path.write_text(new)
            print(f"  updated     {rel}")
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    raise SystemExit(main())
