#!/usr/bin/env python3
"""Status tables, generated. Stdlib only. Run in the maintainers' source, which holds the rubrics.

    python tools/status.py            # rewrite every generated region in place
    python tools/status.py --check    # exit 1 if any generated region is stale (CI)

Every MODULES.md used to carry a hand-copied status table whose header claimed the numbers were
"written back by tools/execute.py and tools/grade.py". Neither tool wrote that file, and the
tables went stale twice: rubric points changed under review and nobody re-copied them. So the
tables are now GENERATED, between markers, from the only sources that can be trusted:

  * which modules exist ........ the lesson directories themselves
  * module numbers and titles .. each MODULES.md's own "## N." / "## Module N —" headings
  * built vs in review ......... meta.yaml `status` (reviewed = built)
  * seconds and peak MiB ....... meta.yaml, as MEASURED and written back by tools/execute.py
  * rubric points and cases .... parsed from tests/test_lesson.py's RUBRIC -- never typed

Edit the lessons, not the tables.
"""
import ast, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- STATUS:BEGIN generated by tools/status.py from the lessons themselves; do not edit -->"
END = "<!-- STATUS:END -->"
sys.path.insert(0, str(ROOT / "internal"))
try:
    import release                     # maintainers' hooks, not part of this repository
except ImportError:
    release = None
HELD = release.held_back() if release else set()


def public(d: Path) -> bool:
    return d.name[:7] not in HELD


HEADING = re.compile(r"^## (?:Module )?(\d+)(?:\.|\s+—)\s+(.+?)\s*$", re.M)
STATUS_SUFFIX = re.compile(r"\s*(?:—\s*)?(?:\*\*BUILT\*\*|\*\(?specified\)?\*|\*specified\*)\s*$")


def meta(d: Path) -> dict:
    out = {}
    for line in (d / "meta.yaml").read_text().splitlines():
        m = re.match(r"^([a-z_]+):\s*(.+?)\s*$", line)
        if m:
            out[m.group(1)] = re.sub(r"\s+#.*$", "", m.group(2)).strip().strip('"\'')
    return out


def rubric(d: Path) -> tuple:
    """(points, cases) summed from the RUBRIC list literal in tests/test_lesson.py."""
    tree = ast.parse((d / "tests" / "test_lesson.py").read_text())
    lists = {t.id: node.value for node in ast.walk(tree) if isinstance(node, ast.Assign)
             for t in node.targets if isinstance(t, ast.Name)}

    def rows(v):
        # a list literal, a name bound to one, or lists joined with + (per-exercise sub-rubrics)
        if isinstance(v, (ast.List, ast.Tuple)) and not (len(v.elts) == 3 and isinstance(v.elts[1], ast.Constant)):
            return [e for e in v.elts if isinstance(e, ast.Tuple)]
        if isinstance(v, ast.BinOp) and isinstance(v.op, ast.Add):
            return rows(v.left) + rows(v.right)
        if isinstance(v, ast.Name) and v.id in lists:
            return rows(lists[v.id])
        return []

    if "RUBRIC" not in lists:
        return 0, 0
    found = rows(lists["RUBRIC"])
    pts = sum(e.elts[1].value for e in found if isinstance(e.elts[1], ast.Constant))
    return pts, len(found)


def fmt_secs(s: str) -> str:
    try:
        v = float(s)
    except (TypeError, ValueError):
        return "—"
    return "<0.1 s" if v < 0.1 else f"{v:.1f} s"


def programme_rows(prog: Path) -> list:
    text = (prog / "MODULES.md").read_text()
    lessons = {int(m.group(1)): p for p in (prog / "lessons").glob("*/")
               if (m := re.match(r"P\d\d-L(\d\d)", p.name)) and (p / "meta.yaml").exists() and public(p)}
    rows = []
    for m in HEADING.finditer(text):
        n = int(m.group(1))
        title = STATUS_SUFFIX.sub("", m.group(2))
        title = re.split(r"\s+—\s+", title, maxsplit=1)[0].strip()
        head, sep, _ = title.partition(": ")
        if sep and len(head.split()) >= 3:      # "Capstone: a monitoring programme ..." keeps its name
            title = head
        d = lessons.get(n)
        if d is None:
            rows.append((n, title, "specified", "—", "—", "—", "—"))
            continue
        mt = meta(d)
        pts, cases = rubric(d)
        status = "**built**" if mt.get("status") == "reviewed" else f"in review ({mt.get('status', '?')})"
        lang = {"c": "**C**", "cpp": "**C++**"}.get(mt.get("language", "python"), "python")
        measured = f"{fmt_secs(mt.get('measured_seconds'))} · {mt.get('measured_peak_mib', '—')} MiB"
        rows.append((n, title, status, f"`{d.name}`", lang, measured, f"{pts} pts / {cases} cases"))
    return sorted(rows)


def programme_region(prog: Path) -> str:
    rows = programme_rows(prog)
    built = sum(r[2] == "**built**" for r in rows)
    lines = [BEGIN, "",
             f"**{built} of {len(rows)} modules built.** A module is built when its lesson directory "
             "exists and has passed all 14 gates in `QUALITY.md` and an independent review; "
             "everything else is specified here and has no directory. Seconds and peak memory are "
             "measured by `tools/execute.py`; rubric size is read from each lesson's "
             "`tests/test_lesson.py`. Regenerate with `python tools/status.py`.", "",
             "| # | Module | Status | Lesson | Language | Measured | Rubric |",
             "|---|---|---|---|---|---|---|"]
    lines += [f"| {n} | {t} | {s} | {l} | {lang} | {me} | {ru} |" for n, t, s, l, lang, me, ru in rows]
    return "\n".join(lines + ["", END])


def readme_region() -> str:
    def count(pattern):
        ds = [p for p in ROOT.glob(pattern) if (p / "meta.yaml").exists() and public(p)]
        return ds, sum(meta(p).get("status") == "reviewed" for p in ds)
    rows, total = [], 0
    for fl in sorted(ROOT.glob("flagships/*/")):
        ds, ok = count(f"flagships/{fl.name}/lessons/*/")
        total += len(ds)
        rows.append(f"| `flagships/{fl.name}` | {ok} lessons{' + capstone' if (fl / 'capstone').is_dir() else ''} | — |")
    ds, ok = count("lessons/*/")
    total += len(ds)
    rows.append(f"| `lessons/` — track lessons | {ok} | — |")
    for prog in sorted(ROOT.glob("programmes/*/")):
        r = programme_rows(prog)
        b = sum(x[2] == "**built**" for x in r)
        total += sum(x[3] != "—" for x in r)
        rows.append(f"| `programmes/{prog.name}` | {b} of {len(r)} | {len(r) - b} |")
    every = [p for pat in ("lessons/*/", "flagships/*/lessons/*/", "programmes/*/lessons/*/")
             for p in ROOT.glob(pat) if (p / "meta.yaml").exists() and public(p)]
    compiled = sum(meta(p).get("language") in ("c", "cpp") for p in every)
    reviewed = sum(meta(p).get("status") == "reviewed" for p in every)
    headline = (f"**{total} lessons, every one passing all 14 gates in `QUALITY.md` and independently "
                "reviewed.**" if reviewed == total == len(every) else
                f"**{len(every)} lessons, {reviewed} of them passed and independently reviewed.**")
    return "\n".join([BEGIN, "",
        f"{headline} {compiled} are compiled C or C++ exercises. Every notebook opens in Colab, "
        "Kaggle, Binder, Codespaces or local Jupyter. Every `MODULES.md` marks a module built only "
        "when its lesson exists and has passed; everything else says `specified`, and means it.", "",
        "| Area | Built | Specified, not built |", "|---|---|---|", *rows, "", END])


NOTICE_BEGIN = "<!-- NOTICE:BEGIN generated by tools/status.py; do not edit -->"
NOTICE_END = "<!-- NOTICE:END -->"


def course_docs() -> list:
    """Every document a learner reads outside a notebook; each ends with the licence notice."""
    pats = ("programmes/*/README.md", "programmes/*/MODULES.md", "flagships/*/README.md",
            "flagships/*/CAPSTONE.md", "lessons/README.md", "QUALITY.md")
    return sorted(p for pat in pats for p in ROOT.glob(pat))


def notice_region(path: Path) -> str:
    from notebooks import OWNER, YEAR, LICENCE, LICENCE_URL, CONTACT_URL, REPO
    import os
    rel = os.path.relpath(ROOT / "NOTICE", path.parent)
    return "\n".join([NOTICE_BEGIN, "", "---", "",
        f"**Synapsa Commons** · © {YEAR} {OWNER} · licensed under [{LICENCE}]({LICENCE_URL}). "
        "You may use this material to learn and to teach, and copy, fork, share and adapt it. "
        f"You must credit \"Synapsa Commons by {OWNER}\" with a link to "
        f"<https://github.com/{REPO}>, say what you changed, and share adaptations under the same "
        "licence. You may not use it, or anything adapted from it, for commercial advantage or "
        f"payment; for a commercial licence, contact [{OWNER}]({CONTACT_URL}). The full summary "
        f"is in [NOTICE]({rel}); the licence's legal code governs.", "", NOTICE_END])


def splice_notice(path: Path) -> tuple:
    text = path.read_text()
    region = notice_region(path)
    if NOTICE_BEGIN in text:
        new = re.sub(re.escape(NOTICE_BEGIN) + r".*?" + re.escape(NOTICE_END), lambda _: region, text, flags=re.S)
    else:
        new = text.rstrip("\n") + "\n\n" + region + "\n"
    return text, new


COMING_BEGIN = "<!-- COMING:BEGIN generated by tools/status.py; do not edit -->"
COMING_END = "<!-- COMING:END -->"


def coming_region() -> str:
    return "\n".join([COMING_BEGIN, "", *release.roadmap_lines(), "", COMING_END])


def splice(path: Path, region: str) -> tuple:
    text = path.read_text()
    begin, end = (COMING_BEGIN, COMING_END) if region.startswith(COMING_BEGIN) else (BEGIN, END)
    if begin not in text:
        return text, None
    new = re.sub(re.escape(begin) + r".*?" + re.escape(end), lambda _: region, text, flags=re.S)
    return text, new


def main() -> int:
    check = "--check" in sys.argv
    every = [p for pat in ("lessons/*/", "flagships/*/lessons/*/", "programmes/*/lessons/*/")
             for p in ROOT.glob(pat) if (p / "meta.yaml").exists()]
    if any(not (p / "tests" / "test_lesson.py").exists() for p in every):
        print("  these tables are regenerated in the maintainers' source, which holds the rubrics; "
              "nothing to do here")
        return 0
    targets = [(p / "MODULES.md", programme_region(p)) for p in sorted(ROOT.glob("programmes/*/"))]
    targets.append((ROOT / "README.md", readme_region()))
    if release:
        targets.append((ROOT / "README.md", coming_region()))
    stale = 0
    for path, region in targets:
        old, new = splice(path, region)
        rel = path.relative_to(ROOT)
        if new is None:
            print(f"  NO MARKERS  {rel}")
            stale += 1
        elif new == old:
            print(f"  current     {rel}")
        elif check:
            print(f"  STALE       {rel}  (run: python tools/status.py)")
            stale += 1
        else:
            path.write_text(new)
            print(f"  updated     {rel}")
    for path in course_docs():
        old, new = splice_notice(path)
        rel = path.relative_to(ROOT)
        if new == old:
            print(f"  current     {rel} (notice)")
        elif check:
            print(f"  STALE       {rel}  (licence notice missing or edited; run: python tools/status.py)")
            stale += 1
        else:
            path.write_text(new)
            print(f"  updated     {rel} (notice)")
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    raise SystemExit(main())
